import { Sora, Syne } from 'next/font/google'
import clsx from 'clsx'
import './globals.css'

const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora',
})

const syne = Syne({
  subsets: ['latin'],
  variable: '--font-syne',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(sora.variable, syne.variable)}>
        <main>{children}</main>
      </body>
    </html>
  )
}
